host: localhost
target:
    simple: 
        port: 10000
        keys: 
            AppKey: 87ec811eb1b26c3687ec811eb1b26c36
            NwkSKey: 725c7da75acddb2f3129ce1d19419d8d
            AppSKey: 752c31f3f980f5cce261ac2c78df51ee

    full: 
        port: 12234
        keys:
            AppKey: 87ec811eb1b26c3687ec811eb1b26c36
            NwkSKey: 6d8800d37cd5f35e0b0614cc9ab584aa
            AppSKey: 25fe3217eca25b2a10e88d26395b7daf

test_file: test_data/lora_test_data.xlsx
test_cases:
    pull:
        start:
            col: A
            row: 2
        end:
            col: F
            row: 17
            end_row: 17
    push:
        start:
            col: A
            row: 20
        end:
            col: M
            row: 53
            end_row: 53
    join:
        start:
            col: A
            row: 57
        end:
            col: J
            row: 84
            end_row: 84
    stat:
        start:
            col: A
            row: 56
        end:
            col: P
            row: 61
            end_row: 77
    rxpk:
        start:
            col: A
            row: 80
        end:
            col: S
            row: 89
            end_row: 105

log_config:
    connector: /home/houlu/lora/log/lora-network-connector.log
    connector_error: /home/houlu/lora/log/lora-network-connector-ERROR.log
    server: /home/houlu/lora/log/lora-network-server.log
    join: /home/houlu/lora/log/lora-join-server.log
    join_error: /home/houlu/lora/log/lora-join-server/ERROR.log
    application: /home/houlu/lora/log/lora-application-server.log
    simple: /home/houlu/lora/log/lora-simple-server.log
